#
# Build stage
#
FROM maven:3.9.15-eclipse-temurin-25 AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -DskipTests -f /home/app/pom.xml clean package

#
# Package stage
#
FROM maven:3.9.15-eclipse-temurin-25-alpine
COPY --from=build /home/app/target/demo-initial-*.jar /usr/local/lib/app.jar
ARG JVM_OPTS
ENV JVM_OPTS=${JVM_OPTS}
# COPY chatapp.keystore.jks /
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/app.jar"]
