# application.properties
spring.profiles.active=dev,h2

spring.application.name="Web MVC Demo"

server.port=8080

com.example.test=Hallo

# CORS Configuration for class config/CorsConfig
endpoints.web.cors.path-mappings=/**
endpoints.web.cors.allowed-methods=OPTIONS, GET, POST, PUT, DELETE, PATCH
endpoints.web.cors.allowed-headers=*
endpoints.web.cors.allowed-origins=http://localhost:4200, http://localhost:8080

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

