# application.properties
spring.profiles.active=dev,h2

spring.application.name="Web MVC Demo"

server.port=8080

com.example.test=Hallo

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

