# application-dev.properties

logging.level.com.example.demoinitial.config=debug

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.version=@springdoc.version@
springdoc.api-docs.enabled=true

app.server=${APP_URL:http://localhost:8080}
